BEGIN;
INSERT INTO tipsdeck_tips (category_id, tipname, tipdescription, directions, sourcetitle, sourceurl, rating, numraters)
VALUES
    (11, 'Hiccup Cure', 'Have a hiccup you cannot get rid of?  The theory to this trick is that it triggers a gag reflex that overrides hiccups.', 'Stick a cotton swab in your mouth and tickle the uvula.', '"Urawaza": 6 Fascinating Japanese Life Hacks', 'https://www.lifehack.org/articles/lifestyle/%e2%80%9curawaza%e2%80%9d-6-fascinating-japanese-life-hacks.html', 4.5, 5),
    (4, 'Stop Crying Baby', 'Provided baby has fully met all other needs, try this technique to calm the child.  The sound mimics the sound of being in the mother''s womb.', 'Sip some water and swish it in your mouth around the baby''s ear.', '"Urawaza": 6 Fascinating Japanese Life Hacks', 'https://www.lifehack.org/articles/lifestyle/%e2%80%9curawaza%e2%80%9d-6-fascinating-japanese-life-hacks.html', 4.8, 6),
    (3, 'Shiny Hair', 'Aim for shiny hair naturally.', 'Mix white vinegar and tap water in equal parts and apply to hair.', '"Urawaza": 6 Fascinating Japanese Life Hacks', 'https://www.lifehack.org/articles/lifestyle/%e2%80%9curawaza%e2%80%9d-6-fascinating-japanese-life-hacks.html', 4.3, 3),
    (11, 'Paper Shredder Alternative', 'Alternative for shredding paper if you do not own one.  Ink will fade or blur and paper will crumple and fall apart.', 'Place documents in nylon pantyhose and wash them.', '"Urawaza": 6 Fascinating Japanese Life Hacks', 'https://www.lifehack.org/articles/lifestyle/%e2%80%9curawaza%e2%80%9d-6-fascinating-japanese-life-hacks.html', 5, 2), 
    (1, 'Get Rid of Coffee Stains', 'The oxalic acid in spinach is said to pull the coffee stains out but do not use with white fabric.  The green spinach color may dye white.', 'Boil spinach in the water and use the boiled water and a toothbrush to brush out the coffee stains.', '"Urawaza": 6 Fascinating Japanese Life Hacks', 'https://www.lifehack.org/articles/lifestyle/%e2%80%9curawaza%e2%80%9d-6-fascinating-japanese-life-hacks.html', 4.0, 4),
    (1, 'Shrunken Sweater', 'This technique may help your sweater return to the original size.', 'Soak it tap water and hair conditioner for 30 minutes.', '"Urawaza": 6 Fascinating Japanese Life Hacks', 'https://www.lifehack.org/articles/lifestyle/%e2%80%9curawaza%e2%80%9d-6-fascinating-japanese-life-hacks.html', 3.5, 1),
    (2, 'Cool Coffee', 'This treatment is for diluted iced coffee.', 'Brew coffee and pour into ice cube tray and freeze.  When iced, use in your iced coffee.', '50 Food Hacks that are Borderline Genius', 'https://www.lovefood.com/gallerylist/70590/50-food-hacks-that-are-borderline-genius', 0, 0),
    (2, 'Cook potato quickly', 'Boiling potatoes take a long time but if you use this technique you can save some time.', 'Prick potatoes with a fork and microwave for 10 minutes.  Then transfer to preheated hot over to crisp the skin for 10-20 minutes.', '50 Food Hacks that are Borderline Genius', 'https://www.lovefood.com/gallerylist/70590/50-food-hacks-that-are-borderline-genius', 4.5, 8),
    (4, 'Water Toys', 'Tired of baby crying for toys they cannot get in the tub, or not within arms reach?  This technique solves that and bonus is when cleaning up you just pull out the laundry basket and rinse in one shot.', 'Get a clean laundry basket and put baby and toys in it.', '35 Life Hacks for Kids That Make Parenting Easier And More Fun', 'https://www.lifehack.org/articles/lifestyle/28-hacks-that-make-parenting-easier-and-more-fun-for-both-you-and-your-kids.html', 4.4, 10),
    (5, 'Clean cutting board', 'Plastic has a tendency to smell over time and discolor.  This technique will sanitize the surface and eliminate odors.', 'Wash board with warm soapy water, then cut a lemon in half and rub it on the surface of the cutting board.', '"Urawaza": 6 Fascinating Japanese Life Hacks', 'https://www.lifehack.org/articles/lifestyle/%e2%80%9curawaza%e2%80%9d-6-fascinating-japanese-life-hacks.html', 4.2, 1),
    (5, 'Clean oven racks', 'Over racks tend to get dirty and crusty with melted food over time.  This tip will help you clean without using too much elbow grease.  Warning this does not work for rusted oven racks and do not put in tub so rust does not get in tub.', 'Use 6 to 8 dryer sheets in bathtub and set over racks on top.  Turn on hot water and fill tub until racks are covered in several inches of water.  For more power add 1/4 cup of Dawn dish soap.  Let racks soak overnight.  Next day, use dryer sheets in tub or scrubber to clean racks.', 'A Surprising Way To Clean Your Dirty Oven Racks With Ease', 'https://www.onegoodthingbyjillee.com/how-to-clean-dirty-oven-racks/', 5.0, 8),
    (6, 'Cinnamon Substitute', 'Take in less calories and get a kick in your coffee.  This will reduce triglycerides, LDL (bad) cholestorol and blood sugar levels.  Also contains anti-oxidants to boost immune system and may improve brain functions.  Every Starbucks has.', 'Add cinnamon in your coffee instead of sugar.', '43 Science-Backed Health Hacks for Busy People', 'https://open.buffer.com/43-science-backed-health-hacks-busy-people/', 4.8, 5),
    (7, 'Cheaper Flights', 'Airlines and travel sites record the visits with cookies in the browser. This makes the prices rise because those flights have been searched before.  They want impulse buyers so to avoid these mishaps by following the directions below.', 'Switch brower to "Private Browsing" when you book flights.', '45 Travel Hacks that Will Make You A Better Backpacker', 'https://www.hostelworld.com/blog/every-single-travel-hack-you-will-ever-need/', 4.7, 4),
    (6, 'Get Happier', 'Dark chocolate and chewing gum helps regulate cortisol hormone that produces stress and aids in stabilizing metabolism.', 'Chew dark chocolate or chewing gum.', '43 Science-Backed Health Hacks for Busy People', 'https://open.buffer.com/43-science-backed-health-hacks-busy-people/', 4.9, 3),
    (7, 'Jet Lag Aid', 'After a long flight, some experience jet lag, some worse than others.  Use this tip to feel better and feel fresh.', 'Go for a jog.', '45 Travel Hacks that Will Make You A Better Backpacker', 'https://www.hostelworld.com/blog/every-single-travel-hack-you-will-ever-need/', 4.6, 8),
    (8, 'Iron Collar', 'Want to iron your collar but do not want to wait for the iron?  Use this tip to save some time.', 'Use a hair straightener.', '26 Fashion Hacks Every Woman Should Know', 'https://www.whowhatwear.com/fashion-style-hacks-shortcuts-solutions-2014/slide2', 4.5, 2),
    (8, 'Deodorant Stains', 'If you have a deodorant stain and pair of jeans you can remove it together. Warning: Test first in case jean stains.', 'Rub the jeans on the stain.', '26 Fashion Hacks Every Woman Should Know', 'https://www.whowhatwear.com/fashion-style-hacks-shortcuts-solutions-2014/slide2', 4.4, 2),
    (9, 'Camping Light', 'Forgot to bring a flashlight?  All you need is a water bottle and a head lamp or light source to get more.', 'Attach light source to gallon of water to create more ambient light.', '10 Cool and Useful Outdoor Life Hacks That Will Come in Handy', 'https://www.techeblog.com/10-cool-and-useful-outdoor-life-hacks-that-will-come-in-handy/', 4.3, 4),
    (9, 'Pillow', 'Forgot a pillow and found the ground to be more uncomfortable than you thought?  This tip also aids in providing more space in your', 'Fill a ziploc bag with air.', '10 Cool and Useful Outdoor Life Hacks That Will Come in Handy', 'https://www.techeblog.com/10-cool-and-useful-outdoor-life-hacks-that-will-come-in-handy/', 4.2, 5),
    (10, 'Cable Holder', 'This tip is great if you need a cable holder quick and be decorative.', 'Put a Lego figure on a block and put it on desk.  Run the cable through the figure''s hands.', '58 best tech life hacks ever', 'https://www.pocket-lint.com/apps/news/135709-the-best-tech-life-hacks-ever', 4.1, 3),
    (10, 'Quick speakers', 'If you need the sound on your mobile device to get louder when it is already set at the loudest, do this tip and the sound gets louder.', 'Put the phone in the cup or container with open top.', '58 best tech life hacks ever', 'https://www.pocket-lint.com/apps/news/135709-the-best-tech-life-hacks-ever', 3.9, 3),
    (11, 'Ideal Bedtime', 'If you are an insomniac and want to know the best time to go to bed and wake up for optimal sleep.  Waking between cycles makes you alert and fre', 'Check out a website called sleepyti.me - https://sleepyti.me/ .', '58 best tech life hacks ever', 'https://www.pocket-lint.com/apps/news/135709-the-best-tech-life-hacks-ever', 3.7, 3),
    (11, 'Room Smell', 'This tip is a quick one when the room smells bad and you cannot find an air refreshener.', 'Stick a dryer sheet over the AC or vent and let the air flow.', '100 Incredible Life Hacks That Make Life So Much Easier', 'https://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html', 3.6, 6),
    (3, 'Smile Naturally', 'If it is hard for you to smile naturally try this tip and it will aid in making your smiles for cameras look more genuine.', 'When smiling, squint your eyes a bit and take picture.', '100 Incredible Life Hacks That Make Life So Much Easier', 'https://www.lifehack.org/articles/lifestyle/100-life-hacks-that-make-life-easier.html', 4.8, 10);
COMMIT;





 




     